development:
  adapter: postgresql
  encoding: unicode
  database: InDorse_development
  pool: 5
  username: deep
  password: 123deep
test:
  adapter: postgresql
  encoding: unicode
  database: InDorse_test
  pool: 5
  username: deep
  password: 123deep
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: InDorse_production
  pool: 5
  username: deep
  password: 123deep
  host: localhost