development:
  adapter: postgresql
  encoding: unicode
  database: InDorse_development
  pool: 5
  username: postgres
  password: nikhil
test:
  adapter: postgresql
  encoding: unicode
  database: InDorse_test
  pool: 5
  username: postgres
  password: nikhil
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: InDorse_production
  pool: 5
  username: postgres
  password: nikhil
  host: localhost