# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa28dacd09a04093bf15e771e9a3e17c245d0f0e66e3a378336a0773a801ec7ed9e007429c42af71e3206a70e3408bf57d60d15fe355f5c5646f3d9c708b304d
  user_name: shantilal@complitech.net
  password: 0FGyLjvLJOv41mzJSRxUOA
  host: "http://192.168.1.20:4000"
  APNS_HOST: 'gateway.push.apple.com' # 'gateway.sandbox.push.apple.com'
  APNS_PORT: 2195
  APNS_PEM: <%= "#{Rails.root}/config/InDorse_apns_prod.pem" %>

test:
  secret_key_base: ce95aeb9d7c64783679d8c87516fa55f84cf0c2f80f3ae7ffcf2293de39683e3b356ae276e26abbccb4321dea9295a6f510e5e9397bdf52006980373330e547a

staging:
  secret_key_base: 50ddca36b9567c4ede43ad1ad281de7ee0e4cf90fae80d8bfd1a170aa8233fed5c0b511eb8f45175f95cd2c3b76dbb5da7e1845bdc00359c4de80e2ade44a04e
  host: "http://indorse.designli.us"
  user_name: shantilal@complitech.net
  password: 0FGyLjvLJOv41mzJSRxUOA
  APNS_HOST: 'gateway.push.apple.com' #'gateway.sandbox.push.apple.com'
  APNS_PORT: 2195
  APNS_PEM: <%= "#{Rails.root}/config/InDorse_apns_prod.pem" %>
  
production:
  secret_key_base: ce95aeb9d7c64783679d8c87516fa55f84cf0c2f80f3ae7ffcf2293de39683e3b356ae276e26abbccb4321dea9295a6f510e5e9397bdf52006980373330e547u
  host: "http://45.55.148.39"
  user_name: shantilal@complitech.net
  password: 0FGyLjvLJOv41mzJSRxUOA
  APNS_HOST: 'gateway.push.apple.com' # 'gateway.sandbox.push.apple.com'
  APNS_PORT: 2195
  APNS_PEM: <%= "#{Rails.root}/config/InDorse_apns_prod.pem" %>
